# Generated by Django 2.1.4 on 2018-12-13 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='city')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('desc', models.TextField(verbose_name='organization description')),
                ('hit_nums', models.IntegerField(default=0, verbose_name='number of hits')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='number of favorites')),
                ('cover', models.ImageField(upload_to='org/%Y/%m', verbose_name='cover')),
                ('address', models.CharField(max_length=150, verbose_name='organization address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='city')),
            ],
            options={
                'verbose_name': 'course organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('work_years', models.IntegerField(default=0, verbose_name='years of working')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('post', models.CharField(max_length=50, verbose_name='post')),
                ('style', models.CharField(max_length=50, verbose_name='style')),
                ('hit_nums', models.IntegerField(default=0, verbose_name='number of hits')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='number of favorites')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'teacher',
            },
        ),
    ]
