# Generated by Django 2.1.4 on 2018-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='avatar'),
        ),
    ]
