# Generated by Django 2.1.4 on 2018-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='famous', max_length=10, verbose_name='organization tag'),
        ),
    ]
