# Generated by Django 2.1.4 on 2018-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181215_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='favorite type id'),
        ),
    ]
