# Generated by Django 2.1.4 on 2018-12-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181215_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover'),
        ),
    ]
