# Generated by Django 2.1.4 on 2018-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.CharField(default='', max_length=300, verbose_name='notes of course'),
        ),
        migrations.AddField(
            model_name='course',
            name='target',
            field=models.CharField(default='', max_length=300, verbose_name='targets of course'),
        ),
    ]
