# Generated by Django 2.1.4 on 2018-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20181217_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_slide',
            field=models.BooleanField(default=False, verbose_name='is slide'),
        ),
    ]
