# Generated by Django 2.1.4 on 2018-12-15 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181214_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauthcode',
            options={'verbose_name': 'Email Auth Code'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Info'},
        ),
        migrations.AlterField(
            model_name='emailauthcode',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='send time'),
        ),
        migrations.AlterField(
            model_name='emailauthcode',
            name='send_type',
            field=models.CharField(choices=[('register', 'register'), ('forget', 'retrieve password')], max_length=10, verbose_name='auth code type'),
        ),
    ]
